/**
 * 🎬 SHOW MANAGEMENT API
 *
 * Endpoints для управления шоу и экспорта логов
 */

import express from "express";
import PDFDocument from "pdfkit";
import { promises as fs } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import PostShowReportService from "../services/postShowReportService.js";
import { baseLogger } from "../middlewares/logger.js";

const router = express.Router();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const LOGS_DIR = path.join(__dirname, "../../data/show/logs");
const reportService = new PostShowReportService();

// Ensure logs directory exists
async function ensureLogsDir() {
  await fs.mkdir(LOGS_DIR, { recursive: true });
}

/**
 * POST /api/show/export-log
 * Экспорт cue log в PDF
 */
router.post("/export-log", async (req, res) => {
  try {
    await ensureLogsDir();

    const { cueLog, venueProfile, showMode, timestamp } = req.body;

    if (!cueLog || !Array.isArray(cueLog)) {
      return res.status(400).json({ error: "Invalid cue log" });
    }

    // Создать PDF
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
    });

    // Set response headers
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="show-log-${Date.now()}.pdf"`,
    );

    // Pipe PDF to response
    doc.pipe(res);

    // Header
    doc
      .fontSize(24)
      .font("Helvetica-Bold")
      .text("HAORI VISION", { align: "center" });

    doc
      .fontSize(16)
      .font("Helvetica")
      .text("Eclipse of Light — Show Log", { align: "center" })
      .moveDown();

    // Metadata
    doc
      .fontSize(10)
      .font("Helvetica")
      .text(`Date: ${new Date(timestamp).toLocaleString()}`, { align: "left" })
      .text(`Mode: ${showMode.toUpperCase()}`, { align: "left" })
      .text(`Venue: ${venueProfile ? venueProfile.name : "N/A"}`, {
        align: "left",
      })
      .text(`Total Cues: ${cueLog.length}`, { align: "left" })
      .moveDown(2);

    // Separator
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();

    doc.moveDown();

    // Table header
    doc
      .fontSize(9)
      .font("Helvetica-Bold")
      .text("TIME", 50, doc.y, { width: 80, continued: true })
      .text("TYPE", 130, doc.y, { width: 80, continued: true })
      .text("DATA", 210, doc.y, { width: 340 });

    doc.moveDown(0.5);

    // Separator
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();

    doc.moveDown(0.5);

    // Cue entries
    doc.font("Helvetica");

    for (const entry of cueLog) {
      // Check if we need a new page
      if (doc.y > 720) {
        doc.addPage();
        doc.fontSize(9);
      }

      const dataText =
        typeof entry.data === "object"
          ? JSON.stringify(entry.data)
          : String(entry.data);

      doc
        .fontSize(8)
        .text(entry.time, 50, doc.y, { width: 80, continued: true })
        .text(entry.type.toUpperCase(), 130, doc.y, {
          width: 80,
          continued: true,
        })
        .text(dataText.substring(0, 100), 210, doc.y, { width: 340 });

      doc.moveDown(0.3);
    }

    // Footer
    doc
      .fontSize(8)
      .font("Helvetica-Oblique")
      .text("Generated by HAORI VISION Show Control System", 50, 770, {
        align: "center",
      });

    // Finalize PDF
    doc.end();

    baseLogger.info(`[Show] Show log exported: ${cueLog.length} cues`);
  } catch (error) {
    baseLogger.error({ err: error }, "[Show] Export failed");
    res.status(500).json({ error: "Export failed" });
  }
});

/**
 * POST /api/show/post-show-report
 * Генерация полного отчёта после шоу
 */
router.post("/post-show-report", async (req, res) => {
  try {
    const showData = req.body;

    if (!showData) {
      return res.status(400).json({ error: "Show data required" });
    }

    baseLogger.info("[Show] Generating Post-Show Report...");

    const result = await reportService.generateReport(showData);

    if (!result.filepath) {
      throw new Error("Report generation failed");
    }

    // Read the generated PDF
    const pdfBuffer = await fs.readFile(result.filepath);

    // Set response headers
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${result.filename}"`,
    );

    // Send PDF
    res.send(pdfBuffer);

    baseLogger.info(`[Show] Post-Show Report generated: ${result.filename}`);
  } catch (error) {
    baseLogger.error({ err: error }, "[Show] Post-Show Report failed");
    res
      .status(500)
      .json({ error: "Report generation failed", details: error.message });
  }
});

/**
 * GET /api/show/status
 * Получить статус системы
 */
router.get("/status", async (req, res) => {
  try {
    const status = {
      timestamp: new Date().toISOString(),
      server: {
        uptime: process.uptime(),
        memory: process.memoryUsage(),
        platform: process.platform,
      },
      show: {
        mode: "idle",
        fps: 60,
        audioClockSync: true,
        dmxLink: false,
        projectorLink: false,
      },
    };

    res.json(status);
  } catch (error) {
    baseLogger.error({ err: error }, "[Show] Status failed");
    res.status(500).json({ error: "Failed to get status" });
  }
});

export default router;
