services:
  - type: web
    name: haorivision-api
    runtime: node
    region: frankfurt
    rootDir: backend
    buildCommand: npm install && node scripts/seedAll.js
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3010
      - key: MONGODB_URI
        value: mongodb+srv://buddapeshtstroganov_db_user:123321@cluster0.n21azq9.mongodb.net/haorivision?retryWrites=true&w=majority
      - key: CLIENT_URL
        value: https://haorivision.netlify.app
      - key: JWT_SECRET
        value: haorivision-jwt-secret-2026-prod-xk9m2
      - key: SESSION_SECRET
        value: haorivision-session-secret-2026-prod-zp4q
      - key: STRIPE_SECRET_KEY
        value: sk_test_replace
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_test_replace
      - key: STRIPE_CURRENCY
        value: rub
      - key: BASE_URL
        value: https://haorivision.com
